site_name: Kursus Kilat Python
theme: 'material'

pages:
- Pengenalan: 'index.md'
- Bab 1 - Memulai: 'bab1.md'
#      - 'Writing your docs': 'tes1.md'
#      - 'Styling your docs': 'tes2.md'
  #- About:
  #     - 'License': 'about/license.md'
  #     - 'Release Notes': 'about/release-notes.md'
